// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaalwEm3FDk83j1bzJAnzL1SZdE1qW1nw',
    appId: '1:37403988148:web:4d82400e81cca6bbe907e1',
    messagingSenderId: '37403988148',
    projectId: 'app-list-clients',
    authDomain: 'app-list-clients.firebaseapp.com',
    storageBucket: 'app-list-clients.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTrohwiDeGcV3D7kg4mLMbeXTIhGJF-M',
    appId: '1:37403988148:android:9b3549ee5eff66b6e907e1',
    messagingSenderId: '37403988148',
    projectId: 'app-list-clients',
    storageBucket: 'app-list-clients.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADoUd8dqhpvOiFpNdO8Kao2PRfi3MkaGs',
    appId: '1:37403988148:ios:b1eb5ffb3e6067b1e907e1',
    messagingSenderId: '37403988148',
    projectId: 'app-list-clients',
    storageBucket: 'app-list-clients.appspot.com',
    iosClientId: '37403988148-5236t16vv2fimcugi4ek99hlule5ubic.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMenezes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADoUd8dqhpvOiFpNdO8Kao2PRfi3MkaGs',
    appId: '1:37403988148:ios:b1eb5ffb3e6067b1e907e1',
    messagingSenderId: '37403988148',
    projectId: 'app-list-clients',
    storageBucket: 'app-list-clients.appspot.com',
    iosClientId: '37403988148-5236t16vv2fimcugi4ek99hlule5ubic.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMenezes',
  );
}
